version: '2.2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  django:
    build: ./server
    command: ["python", "manage.py", "runserver", "127.0.0.1:8000"]
    volumes:
      - ./api:/app/server
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/client
      - node-modules:/app/client/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
